### ISSUE TITLE
Infinite looping

### ISSUE THREAD

**Issue by meenctg** [iamcal/SQLParser#12]
First, thank you for your efforts. I have tried your library, It works great for valid table schema but It does not throw any exception for invalid inputs. When I put invalid input it does not validate the schema and continuously loading and hang my pc.

User can unintentionally or intentionally put any kind of mistake. Like below
```sql
' CREATE TABLE `users` (
        `id` int(10),
        `username` varchar(20) DEFAULT NULL
)
```

```sql
CREATE TABLE `users` '; 1 or 1;(
        `id` int(10),
        `username` varchar(20) DEFAULT NULL
)
```

**Comment by iamcal** [comment]
(Very late response, sorry!) Good catch - I've patched that issue (we detected non-terminating strings, but didn't update the cursor correctly, unlike with comments), and also added an optional mode to throw errors on encountering runway strings or comments.
