### ISSUE TITLE
add support for the BOOLEAN type

### ISSUE THREAD

**Issue by ckhung** [iamcal/SQLParser#13]
Hi, thank you! Your code saved my day.
I have written a small script to convert the json file generated by iamcal/SQLParser to the .er text file required by BurntSushi/erd :
https://gist.github.com/ckhung/c208ad5b72e7ebe216fd0bfc7fb1cb7a
One minor problem is that presently SQLParser does not support the BOOLEAN type.
So as a temporary hack I added
```case 'BOOLEAN':```
alongside
```case 'BINARY':```
Can you please give the correct fix? Thanks!

**Comment by iamcal** [comment]
fixed on master, along with some other missing field types - thanks for the report!
