### ISSUE TITLE
Deprecated: Creation of dynamic property iamcal\SQLParser::$sql is deprecated

### ISSUE THREAD

**Issue by stAn47** [iamcal/SQLParser#25]
Hello, please add

private $sql = ''; 

to SQLParser.php file for php8.3+ compatibility. 

or extend from stdClass if dynamic properties are needed. 

best regards, stan

**Comment by iamcal** [comment]
Can you describe the problem? `$sql` is already declared as a public var and the tests are passing fine under PHP 8.3

**Comment by zepfietje** [comment]
Hey @stAn47 @iamcal, I think the issue here is that the commit that added the `$sql` property (https://github.com/iamcal/SQLParser/commit/1fe57fa39d6de91fc7a2988a7d0c205becbcf341) hasn't been included in a release on Packagist yet.

Tagging a new release should solve it. 😊

**Comment by iamcal** [comment]
Ahh, that makes sense. v0.5 is now on Packagist: https://packagist.org/packages/iamcal/sql-parser

**Comment by zepfietje** [comment]
Thanks, Cal!
