### ISSUE TITLE
You may also be interested in the work done over here...

### ISSUE THREAD

**Issue by iarna** [iamcal/SQLParser#6]
At my last employer I made a tool called [Modyllic](https://github.com/onlinebuddies/modyllic) which is also in PHP and also does both the MySQL parsing and schema diffing. The diff format being a series of SQL schema mutation commands (eg `ALTER TABLE...`). Along with that was a tool for applying of diffs in a way that can be resumed if there are errors.

We actually used a bunch of SQL files on disk to define our schema and used the tool to generate change sets to apply when migrating the database during a release. (And to apply the change sets automatically in dev.)

Regardless, I'm excited to see more folks taking this approach!

**Comment by iamcal** [comment]
(Very late reply) Thanks! I've added a link in the readme
